export const MovieData=[
{
id : 1,
title : "The avengers",
description : "Science-fiction / Action",
posterURL : "https://terrigen-cdn-dev.marvel.com/content/prod/1x/theavengers_lob_crd_03.jpg",
rate : 8,
},
{
id : 2,
title : "Encanto",
description : "Animation / Comedie / Drama",
posterURL : "https://m.media-amazon.com/images/M/MV5BNjE5NzA4ZDctOTJkZi00NzM0LTkwOTYtMDI4MmNkMzIxODhkXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_.jpg",
rate : 7.5,
},
{
id : 3,
title : "Titanic",
description : "Romance / Drama",
posterURL : "https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png",
rate : 8,
},
{
id : 4,
title : "Scream",
description : "Horror / Mysterie",
posterURL : "https://m.media-amazon.com/images/M/MV5BYjExYTcwYmYtMWY2Zi00MGJlLTk3YjUtZTU1Zjg4MDc0Y2FjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_FMjpg_UX1000_.jpg",
rate : 6.5,
},
{
id : 5,
title : "The takedown",
description : "Action / Comedie / Crime",
posterURL : "https://m.media-amazon.com/images/M/MV5BZjNmMWFjZmUtZWYyMy00YTE4LTlhNzEtMTBlMGFkMzNmOTE3XkEyXkFqcGdeQXVyNjE4ODA3NTY@._V1_.jpg",
rate : 5.7,
},
{
id : 6,
title : "Ocean's eight",
description : "Crime / Action / Comedie",
posterURL : "https://upload.wikimedia.org/wikipedia/en/d/dd/OceansEightPoster.jpeg",
rate : 6.2,
},
{
id : 7,
title : "Umma",
description : "Drama / Horror",
posterURL : "https://m.media-amazon.com/images/M/MV5BNDA4NzdiOTItZWUzOC00OWJkLWI4NjQtN2E5N2VjNzMyMTU3XkEyXkFqcGdeQXVyMTAwMjIyMTY4._V1_.jpg",
rate : 4.6,
},
{
id : 8,
title : "Home alone",
description : "comedie",
posterURL : "https://m.media-amazon.com/images/M/MV5BMzFkM2YwOTQtYzk2Mi00N2VlLWE3NTItN2YwNDg1YmY0ZDNmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
rate : 7.6,
},
{
id : 9,
title : "La La Land",
description : "Musical / Romance",
posterURL : "https://thumbs.static-thomann.de/thumb/padthumb600x600/pics/bdb/423957/16443576_800.jpg",
rate : 8,
},
{
id : 10,
title : "The shadow in my eye",
description : "Historical / Drama",
posterURL : "https://m.media-amazon.com/images/M/MV5BNzYzZTgxMTQtYTlhYy00OGJkLThkMGEtNjlhZTRkNDIwZTkyXkEyXkFqcGdeQXVyMTM0NTc2NDgw._V1_FMjpg_UX1000_.jpg",
rate : 7.3,
},
{
id : 11,
title : "The Lost City",
description : "Action / Comedie",
posterURL : "https://dx35vtwkllhj9.cloudfront.net/paramountpictures/the-lost-city/images/regions/us/onesheet.jpg",
rate : 6.3,
},
{
id : 12,
title : "The Lion King",
description : "Animation / Drama / Musical",
posterURL : "https://m.media-amazon.com/images/M/MV5BMjIwMjE1Nzc4NV5BMl5BanBnXkFtZTgwNDg4OTA1NzM@._V1_FMjpg_UX1000_.jpg",
rate : 6.9,
},
]